### ISSUE TITLE
Write Documentation

### ISSUE THREAD

**Issue by tomschr** [openSUSE/dbxincluder#10]
At the moment, we don't have any up-to-date documentation. I think, you could improve that with the follwoing:
- Write documentation in Sphinx/ReST format.
- Use `.bumpversion.cfg` and add `doc/conf.py` as configuration.
- Create the structure in a `docs` subdirectory. You can use `sphinx-quickstart` which asks you questions about what you want
- Ignore the `build` and `dist` directories

The documentation itself should contain the following key points:
- What is `dbxincluder`?
- Short introduction about Transclusion
- Feature Highlights
- Installation Requirements and supported Python version(s)
- Supported Attributes
- Maybe a concise example
- A manpage

Maybe you find additional or better entries. Think about what the _user_ wants to know about this project.

Find some doc examples in KIWI: https://github.com/SUSE/kiwi/tree/master/doc/source

**Comment by Vogtinator** [comment]
All important topics are now documented and a manpage is there as well.
There's still some room for improvement, but I consider this good enough for now.
