### ISSUE TITLE
Deploy Documentation on GitHub Pages

### ISSUE THREAD

**Issue by tomschr** [openSUSE/dbxincluder#11]
It would be nice to have an up-to-date documentation published on GitHub Pages after a successful Travis build.

Requirements:
- A `gh-pages` branch
- Require `travis-sphinx` in `text_requirement.txt` or in `tox.ini`
- Update `tox.ini` with a `doc_travis_deploy`, see https://github.com/SUSE/kiwi/blob/master/tox.ini#L84 for an example.
- Update `.travis.yml`

It should limit the build for the `master` and `develop` branches only (use the `--branches` option). You also need to create a token on GitHub which is then pasted in the Travis settings dialog. Find more information on its homepage https://github.com/Syntaf/travis-sphinx

**Comment by Vogtinator** [comment]
> It should limit the build for the master and develop branches only

Isn't it either-or? Wouldn't the documentation for develop overwrite the documentation for master if both branches are specified?

**Comment by tomschr** [comment]
> Isn't it either-or? Wouldn't the documentation for develop overwrite the documentation for master if both branches are specified?

Good catch. Probably yes. The question is, if we want it. 

My assumption was that both are (should be?) useful. When you create a release on master, it should overwrite anything that was deployed on develop before. On the other side, if you change anything in develop, it will be also published (assuming the there are doc changes).

If we allow publishing only on master, documentation is not always up-to-date. Depends probably on how often we create a release.

I'm open for suggestions. :)

**Comment by Vogtinator** [comment]
I wonder if is possible with travis-sphinx to upload the documentation into a subdirectory on gh-pages.
I doubt that though, as that sounds like it breaks down with concurrent builds.

**Comment by tomschr** [comment]
> I wonder if is possible with travis-sphinx to upload the documentation into a subdirectory on gh-pages.

As far as I know, I don't think this is possible.

**Comment by Vogtinator** [comment]
IMO it makes sense to only deploy documentation of the master branch.
Those using the develop branch either don't need the documentation or are able to build it manually.

**Comment by Vogtinator** [comment]
I'll implement this after there is a generatable documentation in the master branch.

**Comment by tomschr** [comment]
Sounds good to me. :+1:

**Comment by Vogtinator** [comment]
Fixed, now with a clean usable design: https://opensuse.github.io/dbxincluder
