### ISSUE TITLE
Improve Modularization and Maintenance

### ISSUE THREAD

**Issue by tomschr** [openSUSE/dbxincluder#12]
In order to improve maintenance, I would suggest some changes:
- Try to move everything (except `__version__`) in `__init__.py` into (a) different file(s).
  
  It's common practise in Python to have mostly empty `__init__.py` files, maybe with a version string.
- Use `argparse` in the function `main()` (maybe `docopt` is also an option).
  
  At the moment we don't have any other options. However, as soon as we are adding more, it's better to do it with the right library module for this pupose.
- Make sure the project can also be used as a library (which is probably already the case).

**Comment by Vogtinator** [comment]
> Make sure the project can also be used as a library (which is probably already the case).

Yes, that's how the tests (except for main) are implemented.

**Comment by Vogtinator** [comment]
Using docopt now!

**Comment by tomschr** [comment]
Great! :+1:
