### ISSUE TITLE
Use Test Coverage with pytest-cov

### ISSUE THREAD

**Issue by tomschr** [openSUSE/dbxincluder#13]
I would like to see some test coverage reports. :) 

Requirements:
- Use the `pytest-cov` package
- Distinguish in `tox.ini` between a "normal" test run and a test run with coverage enabled
- The "coverage ..." calls can be replaced by:
  
  ```
  {posargs:py.test --cov=dbxincluder --cov-fail-under=90 --cov-report=term-missing -vv}
  ```

**Comment by Vogtinator** [comment]
That's done even before the first line of code got written.

[![Coverage Status](https://coveralls.io/repos/github/openSUSE/dbxincluder/badge.svg?branch=feature%2Frewrite)](https://coveralls.io/github/openSUSE/dbxincluder?branch=feature%2Frewrite)
