### ISSUE TITLE
Check flake8 output

### ISSUE THREAD

**Issue by tomschr** [openSUSE/dbxincluder#14]
[Flake8](https://pypi.python.org/pypi/flake8) is a modular source code checker for Python. It reports inconsistencies and style issues.

Install the `flake8` script with `pip install flake8` in your virtual environment and run it with:

```
$ flake8 src/dbxincluder
```

Check the output and fix it, if necessary. Probably you need to set the maximum character in a line a bit higher.

Include it also as a target in `tox.ini`

**Comment by Vogtinator** [comment]
Already done by landscape and most IDEs.

[![Code Health](https://landscape.io/github/openSUSE/dbxincluder/develop/landscape.svg?style=flat)](https://landscape.io/github/openSUSE/dbxincluder/develop)
