### ISSUE TITLE
Improve error message (trans:idfixup)

### ISSUE THREAD

**Issue by tomschr** [openSUSE/dbxincluder#22]
According to the [DocBook Transclusion spec](http://docbook.org/docs/transclusion/#idfixup-attribute), the `trans:idfixup` can have one of the values `none`, `suffix`, or `auto`.

When using `trans:idfixup` with `foo` as an invalid value, I get:

```
Error at tests/db/blub.xml:7: idfixup type 'foo' not implemented
Included by tests/db/article.01.xml
```

The error itself is correct of course, but the message is misleading. I was confused too at a first glance. ;-)
To make it more clear, I would propose to change it like this:

```
Error at tests/db/blub.xml:7: idfixup contains 'foo', but only 'none', 'suffix', or 'auto' are allowed.
```

I think that makes it clearer.

**Comment by Vogtinator** [comment]
Fixed.
