### ISSUE TITLE
Allow referencing to the same document

### ISSUE THREAD

**Issue by tomschr** [openSUSE/dbxincluder#24]
According to the XInclude spec, the [href attribute](https://www.w3.org/TR/xinclude-11/#include_element) is optional:

> The href attribute is optional; the absence of this attribute is the same as specifying href="", that is, the reference is to the same document.

I think it does make sense to allow referencing and including parts from the same document.

Some ideas:
- When there is no `href` attribute (or `href="`), the spec requires to have either an `xpointer` or `fragid` attribute.
- ATM it's enough to support `fragid` only.
- I think, we should also check if `set-xml-id` is there. We don't want the same IDs in the result document.
- If there is no such an attribute, should dbxincluder print a warning? Abort?

**Comment by Vogtinator** [comment]
> I think, we should also check if set-xml-id is there. We don't want the same IDs in the result document.

There are documents that have no xml:id anywhere, so set-xml-id isn't required. Also, the spec says that XInclude can generate invalid documents, so not allowing that would be an error.

**Comment by Vogtinator** [comment]
Implemented.
