### ISSUE TITLE
Support -o/--output option

### ISSUE THREAD

**Issue by tomschr** [openSUSE/dbxincluder#27]
At the moment, the program doesn't have any option where to save the output.

Of course the output could be redirected to a file, but I think it would be nice to have an additional `-o`/`--output` option.

**Comment by Vogtinator** [comment]
I left it out intentionally, there's no reason to have an -o argument (except calling it from C programs where there is no simple way to redirect stdout)

**Comment by tomschr** [comment]
I think it's a good idea and you can find it in lots of programs and scripts. For example,  xmllint has it and many more. It's ubiquitous and good practice. People expect it.

Apart from that I think it makes things a lot easier when implementing logging capabilities for example.

**Comment by Vogtinator** [comment]
Implemented.
