### ISSUE TITLE
Support DocBook transclusion

### ISSUE THREAD

**Issue by tomschr** [openSUSE/dbxincluder#3]
Support the `trans:*` and `local:*` attributes on `<xi:include/>` elements, please. For more information, see http://docbook.org/docs/transclusion

The page contains in section "B. Special ID/IDREF processing" some examples which can be used as a test case (abridged, of course).

**Comment by Vogtinator** [comment]
Obviously implementing the whole spec with 100% conformity is a huge undertaking.
Is there a subset that covers 100% - 1E-10 % of all cases?

**Comment by tomschr** [comment]
I'm thinking more of a first start. :) Maybe we should split this issue into several sub-issues so it's easier to digest.

I'm not aware of a subset yet.

**Comment by Vogtinator** [comment]
Should be done now, all examples from the docbook transclusion draft seem to work!

**Comment by tomschr** [comment]
That's pretty cool! :+1:
