### ISSUE TITLE
Implement inheriting transclusion attributes

### ISSUE THREAD

**Issue by Vogtinator** [openSUSE/dbxincluder#6]
Although I don't see how it can be useful, the trans:suffix and trans:linkscope attribute can be inherited, but trans:idfixup can't.

**Comment by tomschr** [comment]
Why should trans:idfixup be inherited? Not sure if this makes any sense.

**Comment by tomschr** [comment]
I've opened a new thread on the DocBook mailinglist about the inheritance aspect, see https://lists.oasis-open.org/archives/docbook/201605/msg00002.html

**Comment by Vogtinator** [comment]
> Why should trans:idfixup be inherited?

It isn't.

> I've opened a new thread on the DocBook mailinglist about the inheritance aspect, see https://lists.oasis-open.org/archives/docbook/201605/msg00002.html

Inheriting trans:suffix makes at least some sense, as

```
<a trans:idfixup="suffix" trans:suffix="deep">
    <a trans:idfixup="suffix">
      <b xml:id="asdf"/>
      <xref linkend="asdf">
    </a>
</a>
```

will result in 

```
<a>
    <a>
      <b xml:id="asdfdeepdeep"/>
      <xref linkend="asdfdeepdeep">
    </a>
</a>
```

I'm not sure how it can be practical.

**Comment by Vogtinator** [comment]
Implemented!
