### ISSUE TITLE
Make version number consistent (0.0 -> 0.1.0)

### ISSUE THREAD

**Issue by tomschr** [openSUSE/dbxincluder#8]
The `.bumpversion.cfg` configuration file contains version `0.1.0`, but `src/dbxincluder/__init__.py` contains `"0.0"`.

**Comment by Vogtinator** [comment]
Solved by removing bumpversion.

**Comment by tomschr** [comment]
As explained some days ago, I would like to see `bumpversion` again. So removing is not a solution. ;-) Please add that again. Thanks! :+1:
